SEND_DATE_NOW = 'now'

PLATFORM_IOS = 1
PLATFORM_BLACKBERRY = 2
PLATFORM_ANDROID = 3
PLATFORM_ASHA = 4
PLATFORM_WINDOWS_PHONE = 5
PLATFORM_BADA = 6
PLATFORM_OSX = 7
PLATFORM_WINDOWS = 8
PLATFORM_AMAZON = 9
PLATFORM_SAFARI = 10
PLATFORM_CHROME = 11
PLATFORMS = (PLATFORM_IOS, PLATFORM_BLACKBERRY, PLATFORM_ANDROID, PLATFORM_ASHA, PLATFORM_WINDOWS_PHONE, PLATFORM_BADA,
             PLATFORM_OSX, PLATFORM_WINDOWS, PLATFORM_AMAZON, PLATFORM_SAFARI, PLATFORM_CHROME)

PLATFORM_NAMES = {
    PLATFORM_IOS: 'IOS',
    PLATFORM_BLACKBERRY: 'BLACKBERRY',
    PLATFORM_ANDROID: 'ANDROID',
    PLATFORM_ASHA: 'ASHA',
    PLATFORM_WINDOWS_PHONE: 'WINDOWS_PHONE',
    PLATFORM_BADA: 'BADA',
    PLATFORM_OSX: 'OSX',
    PLATFORM_WINDOWS: 'WINDOWS',
    PLATFORM_AMAZON: 'AMAZON',
    PLATFORM_SAFARI: 'SAFARI',
    PLATFORM_CHROME: 'CHROME',
}

LINK_MINIMIZER_NONE = 0
LINK_MINIMIZER_GOOGLE = 1
LINK_MINIMIZER_BITLY = 2
LINK_MINIMIZER_BAIDU = 3
LINK_MINIMIZERS = (LINK_MINIMIZER_NONE, LINK_MINIMIZER_GOOGLE, LINK_MINIMIZER_BITLY, LINK_MINIMIZER_BAIDU)

TAG_FILTER_OPERATOR_GTE = 'GTE'
TAG_FILTER_OPERATOR_LTE = 'LTE'
TAG_FILTER_OPERATOR_EQ = 'EQ'
TAG_FILTER_OPERATOR_NOTEQ = 'NOTEQ'
TAG_FILTER_OPERATOR_BETWEEN = 'BETWEEN'
TAG_FILTER_OPERATOR_IN = 'IN'
TAG_FILTER_OPERATOR_NOTIN = 'NOTIN'
TAG_FILTER_OPERATORS = (TAG_FILTER_OPERATOR_GTE, TAG_FILTER_OPERATOR_LTE, TAG_FILTER_OPERATOR_EQ,
                        TAG_FILTER_OPERATOR_BETWEEN, TAG_FILTER_OPERATOR_IN, TAG_FILTER_OPERATOR_NOTEQ,
                        TAG_FILTER_OPERATOR_NOTIN)
